### ISSUE TITLE
Make dependency on `serde` on generated code optional / document which features are needed

### ISSUE THREAD

**Issue by jorgecarleitao** [TethysSvensson/planus#26]
Every dependency counts, and for users that do not intend to serialize the structs to serde, the dependency may be an extra burden.

Some ideas:
* consider making the dependency optional in the generation step
* consider document that `serde` is required, and document which features of `serde` are required

These may justify a small guide.

**Comment by TethysSvensson** [comment]
I think this should definitely be optional, however it's blocked by #31.

**Comment by TethysSvensson** [comment]
I've opened #31 and #43 to cover the two fixes we want to get done regarding this.
