### ISSUE TITLE
Consider renaming trait `ToOwned` to `TryToOwned`

### ISSUE THREAD

**Issue by jorgecarleitao** [TethysSvensson/planus#30]
The trait's name is confusing because it hints that is infallible, but we do need to parse the struct, making it fallible. As such, it makes more sense to hint that in the name also.

Note that `MosterRef::to_owned` is shadowed by stds' to_owned. E.g. to convert a Vector of MosterRef to a Vec<Monster>, we need to use

```rust
monsters
            .iter()
            .map(|monster| Ok(ToOwned::to_owned(monster)?))
            .collect::<Result<Vec<_>>>()?
```

instead of

```rust
monsters.to_owner()?
```

**Comment by TethysSvensson** [comment]
I think we can actually just get rid of the trait. See #19.
